In [1]:
import numpy as np
print(np.max(1))
a = np.asarray(1)
print(a)

1
1


In [2]:
a = np.asarray([1,2,3,0,4])
is_zero = np.abs(a) < 1e-8
print(is_zero)
a[is_zero] = 100
print(a)
print(np.all(is_zero))

[False False False  True False]
[  1   2   3 100   4]
False


In [4]:
a = np.asarray([[0,1],[2,3],[4,5]])
print(a)
a[1:2,:] = 0
print(a)
a[[0,2],:] = a[[2,0],:]
print(a)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [0 0]
 [4 5]]
[[4 5]
 [0 0]
 [0 1]]
